### ISSUE TITLE
The structure of the datasets

### ISSUE THREAD

**Issue by lk-greenbird** [zonetrooper32/robot_semantics#4]
hi,
I am interested in the great job you have done, and I want to go through it. I have downloaded your dataset from google driver. But how should the data in the dataset  be structured to run your experiments?

**Comment by zonetrooper32** [comment]
Hello,

Thank you for opening this issue. I will do some significant updates in the coming days, which will make this repo runnable again.

For now, keep everything of the dataset unchanged, until the README instruction's updated.
